### ISSUE TITLE
Compilation instructions don't work

### ISSUE THREAD

**Issue by l0b0** [dajobe/flickcurl#29]
There's no `configure` script in the repository as mentioned in the [compilation instructions](http://librdf.org/flickcurl/); I suspect some automake magic has to happen first? `./autogen.sh`? At least that seems to work for me.

**Comment by dajobe** [comment]
Yes it should mention autogen.sh - that's what you need.  But if you build from a tarball, you get configure (and a consistent set of other files) and I recommend that in most cases, unless you are going to develop flickcurl.
