### ISSUE TITLE
people.findByUsername doesn't work with my username

### ISSUE THREAD

**Issue by l0b0** [dajobe/flickcurl#32]
I can't find [my own user](https://www.flickr.com/photos/l0b0/)'s ID with `findByUsername`:

    $ flickcurl people.findByUsername l0b0
    flickcurl: ERROR: Method flickr.people.findByUsername failed with error 1 - User not found
    flickcurl: Command people.findByUsername failed

`people.findByEmail` still works.

    $ flickcurl --version
    1.26

**Comment by dajobe** [comment]
This call for id l0b0 doesn't work from the Flickr API explorer `https://www.flickr.com/services/api/explore/flickr.people.findByUsername` so I think it might be something on the Flickr API side.

**Comment by dajobe** [comment]
Works for me with my ID so I'll probably close this issue.

**Comment by l0b0** [comment]
Alright, I'll try to file a bug upstream.

**Comment by l0b0** [comment]
Just an FYI, [`findByUsername` actually queries the "screen name"](https://www.flickr.com/groups/51035612836@N01/discuss/15593/90870), *not* what people would associate with an actual username (i.e., the string used to log in and in all the URLs).
