### ISSUE TITLE
double free or corruption (!prev):

### ISSUE THREAD

**Issue by jidanni** [dajobe/flickcurl#39]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875800
$ flickcurl oauth.create
*** Error in `flickcurl': double free or corruption (!prev): 0x0176b510 ***
======= Backtrace: =========
/lib/i386-linux-gnu/libc.so.6(+0x698aa)[0xb72e18aa]
/lib/i386-linux-gnu/libc.so.6(+0x705f7)[0xb72e85f7]
/lib/i386-linux-gnu/libc.so.6(+0x70e46)[0xb72e8e46]
/usr/lib/i386-linux-gnu/libflickcurl.so.0(flickcurl_free_form+0x22)[0xb7748a62]
/usr/lib/i386-linux-gnu/libflickcurl.so.0(flickcurl_oauth_create_request_token+0x201)[0xb7766f61]
flickcurl(+0xce50)[0x469e50]
flickcurl(main+0x62c)[0x46425c]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf6)[0xb7290456]
flickcurl(+0x7310)[0x464310]
======= Memory map: ========
0045d000-0047c000 r-xp 00000000 08:08 65457      /usr/bin/flickcurl
0047c000-0047d000 r--p 0001e000 08:08 65457      /usr/bin/flickcurl
0047d000-0047f000 rw-p 0001f000 08:08 65457      /usr/bin/flickcurl
00a1b000-017a5000 rw-p 00000000 00:00 0          [heap]
b4000000-b4021000 rw-p 00000000 00:00 0
b4021000-b4100000 ---p 00000000 00:00 0
b41d4000-b41d9000 r-xp 00000000 08:08 228674     /lib/i386-linux-gnu/libnss_dns-2.25.so
b41d9000-b41da000 r--p 00004000 08:08 228674     /lib/i386-linux-gnu/libnss_dns-2.25.so
b41da000-b41db000 rw-p 00005000 08:08 228674     /lib/i386-linux-gnu/libnss_dns-2.25.so
b41db000-b41e6000 r-xp 00000000 08:08 228676     /lib/i386-linux-gnu/libnss_files-2.25.so...

**Comment by jidanni** [comment]
The Debian bug has been fixed!

**Comment by norayr** [comment]
i had the same problem with double free or corruption, when using flickurl 1.26.

```
free(): double free detected in tcache 2
Aborted
```

however i somehow was able to build the git version.
for some reason autogen.sh was not able to download the submodule libmtwist. so i did it by hand.

```
rmdir libmtwist
git clone git@github.com:dajobe/libmtwist.git
```

then

```
autoheader     && aclocal     && libtoolize --ltdl --copy --force     && automake --add-missing --copy     && autoconf
```

then almost as you suggested somewhere

```
./configure --enable-maintainer-mode --disable-static --disable-gtk-doc --enable-capture --enable-debug --prefix=/opt/flickcurl
```

and that version works!
